version: "3"
services:
  api:
    build: ./api
    ports:
      - "4444:4444"
    depends_on:
      - db
    container_name: InternetShopDiploma-api
  client:
    build: ./client
    ports:
      - "8080:8080"
    container_name: InternetShopDiploma-client
  db:
    image: mysql
    ports:
      - "3307:3306"
    container_name: InternetShopDiploma-db